### ISSUE TITLE
New ETL Output CSV

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/path-zambia-etl#12]
Create a new CSV output which has data aggregated by date for all the aggregations that we typically need.

This would make consumption of the output data much more easier and pleasant.

@claycrosby @jasonrogena @keymane @githengi

**Comment by csc5k** [comment]
Would we store this in a table where each row is a date and each column is the to-date aggregation?

Right now the to-date aggregate numbers we need are:

* total # of penta 1
* total # of penta 3
* total # of measles 1

I'll confirm whether there aren't any more that we'll need

**Comment by moshthepitt** [comment]
@claycrosby I think we could store all the aggregations we need for a date, including any running totals

**Comment by csc5k** [comment]
OK cool, so just to be clear, we're now looking at 3 ETLs total for ZEIR:

1) registrations (ticket #10)
2) encounters (ticket #11)
3) to-date aggregations (this ticket)

Each of these ETLs would correspond to its own table in Superset

I'll update this ticket with any other aggregations we need beyond the 3 listed in my post above

**Comment by csc5k** [comment]
Closing because was able to accomplish this using some nested SQL statements for ZEIR Dropout metrics (tickets #17 and #18 )
